nodes:
  # Wazuh indexer server nodes
  indexer:
    - name: wazuh-indexer-0
      ip: wazuh-indexer-0.wazuh-indexer.default.svc.cluster.local
  dashboard:
    - name: wazuh-dashboard
      ip: wazuh-dashboard.default.svc.cluster.local