nodes:
  # Wazuh indexer nodes
  indexer:
    - name: index-1
      ip: "indexer-1.wazuh-indexer.default.svc.cluster.local"
    #- name: node-2
    #  ip: "<indexer-node-ip>"
    #- name: node-3
    #  ip: "<indexer-node-ip>"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: manager-1
      ip: "manager-1.wazuh-manager.default.svc.cluster.local"
    #  node_type: master
    #- name: wazuh-2
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker
    #- name: wazuh-3
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: "dashboard.wazuh-dashboard.default.svc.cluster.local"